### ISSUE TITLE
How to handle measuring extents of multi-series data

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/layercake#1]
If you want, say, a multi-series line chart, the best data structure would be an array of arrays of objects with the same x and y keys like this

```js
[
  [{x: 1, y: 10},{x: 2, y: 12},{x: 3, y: 15}],
  [{x: 1, y: 20},{x: 2, y: 22},{x: 3, y: 25}]
]
```

The problem is how can [calcExtents](src/utils/calcExtents.js) properly measure the extents of this data?

Consider also this common data structure, which is similar to the output from d3.nest()

```js
[
  {key: 'group1', values: [{x: 1, y: 10},{x: 2, y: 12},{x: 3, y: 15}]},
  {key: 'group2', values: [{x: 1, y: 10},{x: 2, y: 12},{x: 3, y: 15}]}
]
```

#### Option 1, include an option to flatten data one depth down

You could set a property in the store to `flatten: true` which could flatten this data, or have that be the default. This would also then help with D3 stack layouts.

#### Option 2, allow a custom flattening function

Let the user set their own function with `flatten`. This can be annoying though if the user doesn't really want to deal with flattening arrays of arrays properly

#### Option 3, allow pre-flattened data

This has the same problem as 3 but might also be a good idea in general in case the user is already flattening their data elsewhere or maybe it was loaded in flat and then they nested it, they can pass that in we avoid restructuring the data.

#### Thoughts

These aren't mutually exclusive and I could see an argument for including all of them since they offer  convenience for casual users plus escape hatches if things get tricky. 

This in general seems like a messy concept to have to handle but I'm not sure what a good solution is. The "do nothing" solution would be have `calcExtents` balk at anything that is array of arrays and require you to set your domains manually in that scenario. That could be problem though if you have a data structure like this below, which it seems would be silly to not support :

```js
[
  [0, 1], [1, 4]
]
```

**Comment by mhkeller** [comment]
A default of flattening one level down seems sensible, plus an option of `flattenData` which can be `false` to prevent any flattening, a function that tells layercake how to flatten, or an array of pre-flattened data may be the way to go if the sin of mixing types can be forgiven.

**Comment by dhalford** [comment]
It seems that flatten is one type of data transformation, but given that input data may be many different types and the flattened "output" data can also vary maybe this would be better suited as a generic `transform()` operation where the user specifies one of a few transformations or provides a custom function.

Unfortunately `calcExtents` also can't be completely automatic without context of what outcome is going to be - a simple example is that a stacked bar/area chart will have completely different extents with the same data. 

For the base example you have a desired input:
```[
  [{x: 1, y: 10},{x: 2, y: 12},{x: 3, y: 15}],
  [{x: 1, y: 20},{x: 2, y: 22},{x: 3, y: 25}]
]```

But your input data might be an already flattened form like below (that can be parsed into the above):
```[
  [1, 10, 2, 12, 3, 15],
  [1, 20, 2, 22, 3, 25]
]
```

I can think of so many variations of outputs to inputs that it might be better to just have explicit transform operations like `transform(pluckFrom('values', ['x', 'y']))` for: 
```[
  {key: 'group1', values: [{x: 1, y: 10},{x: 2, y: 12},{x: 3, y: 15}]},
  {key: 'group2', values: [{x: 1, y: 10},{x: 2, y: 12},{x: 3, y: 15}]}
]```

**Comment by dhalford** [comment]
Oh and then calcExtents for the transformed might be the following for a multi series stacked domain:  `calcExtents(reduce(minMax('x'), sum('y')))`  -- but even this is difficult because reduce would be operating over "group1" and "group2" (ie for stacked bar you want the minmax of x values, and the sum of y values for the two groups.

**Comment by mhkeller** [comment]
To summarize the offline discussion, it seems the best approach is to allow for a custom flatten function, whose name is tbd. 

In order to solve the most common use case, which is flattening one-level down, layercake can export a helper function in the same way that it exports `newDiv` and `scaleCanvas`. This has the added benefit that if you don't use the flattening function, it will be tree-shaken away.

**Comment by mhkeller** [comment]
And to clarify, the flattener would not change the shape of the data passed to components, it just puts it in a format that the x and y accessors can reach the values.

**Comment by mhkeller** [comment]
We would still want to figure out a way to support data that you have previously flattened, Option 3 above. If this is called `flatten` we could have a `flatData` option.

**Comment by mhkeller** [comment]
This is done now via `.flatten`, which takes a function and `flatData`.
