### ISSUE TITLE
`style` block inside (Svg) Layer Components?

### ISSUE THREAD

**Issue by janwillemtulp** [mhkeller/layercake#102]
Hi, not a bug, maybe a feature request, or at least a question:

am I right that I cannot use a `svelte` `style` block inside an `Svg` Layer component? Svelte gives CSS class names unique hashes, so, what would be a best practice to us CSS classes inside an Svg Layer Component?

Thanks!

**Comment by mhkeller** [comment]
If you want to apply a style to the svg component itself that is not supported. To do this, copy the source code from layercake’s svg component into your project, add whatever customizations you like, and import it. 

If what you’re asking is can one use style tags inside of a renderer, then yes. They are just svelte components and that will work. Most of the examples on the site show that usage.

**Comment by mhkeller** [comment]
Hi, Let me know if this solved it for you.

**Comment by mhkeller** [comment]
I’m going to close this. Let me know if you’re still having issues.
