### ISSUE TITLE
ScatterGl

### ISSUE THREAD

**Issue by dsm-72** [mhkeller/layercake#119]
Please update your example to be able to provide a color key to change color of each point based on another value.
The examples on your site are a bit daunting.
Like why wouldn't I just iterate over my data with pure SVG instead?

**Comment by mhkeller** [comment]
You would generally only need webgl if you had some tremendous amount of points you wanted to plot. Otherwise, using canvas or svg is just fine. What’s your use case?

**Comment by dsm-72** [comment]
@mhkeller data visualization, stuff normally done in a python notebook (10k+ points is the norm). I tried ibm's carbon components but they are too clunky and basically crash

**Comment by mhkeller** [comment]
Did you already try the canvas example? With that many points a scatter plot may not be best. Perhaps some kind of point density chart would work better.

**Comment by dsm-72** [comment]
@mhkeller for the time being I seem to manage it with Canvas. [link to deployment](https://krishnaswamylab.org/phate-browser)

Any experience with performant 3d scatter plots???

**Comment by mhkeller** [comment]
Great – glad you found a solution. I haven't had occasion to make a 3d scatter plot but if you come up with a solution you like and want to contribute an example that would be great.
