### ISSUE TITLE
Color bar component

### ISSUE THREAD

**Issue by janosh** [mhkeller/layercake#120]
For heatmaps, it's often informative to display a color scale bar indicating which colors correspond to which values. See https://github.com/d3/d3-scale-chromatic#diverging for examples.

I started working on an implementation over at https://elementari.janosh.dev/color-bar ([code](https://github.com/janosh/elementari/blob/main/src/lib/ColorBar.svelte#L19)) but maybe it would make a good addition here?

**Comment by mhkeller** [comment]
Yea that would be a great addition to the component gallery. It would be neat if you could specify the number of samples to take and also print out any specified domain values, too.

**Comment by mhkeller** [comment]
It would be nice if the ticks also had a `snapTicks` option, similar to the existing axis component examples. Want to start a PR and we can go from there?

**Comment by mhkeller** [comment]
We have the draft PR so I'm going to close this issue for now and we can use that PR for discussion
