### ISSUE TITLE
yTick in AxisY.svelte changes position of marks and gridlines

### ISSUE THREAD

**Issue by patriciatiffany** [mhkeller/layercake#124]
It seems like the prop yTick in AxisY.svelte changes position of marks and gridlines, not just the text/ label. Is this the intended behaviour? I'm thinking that it shouldn't be, as it compromises the accuracy of the resulting chart.

(I didn't check the matching X axis component, or the HTML equivalents, so the behaviour might be similar in those places as well.)

**Comment by mhkeller** [comment]
Good catch! I added that prop as a convenience / escape hatch so have never set it to anything other than `0`. It looks like it is just that one component, fixed via: https://github.com/mhkeller/layercake/commit/bca0ba2a11c8ff5f2b67ed9026ce88c650d9a3a8

If you spot anything else let me know!

**Comment by patriciatiffany** [comment]
Thanks for the quick response!
