### ISSUE TITLE
Issue with package.json "exports" prop

### ISSUE THREAD

**Issue by bothness** [mhkeller/layercake#132]
I'm getting the following error in a Svelte Kit (javascript) project where layercake is a dependency.

```
Failed to resolve entry for package "layercake". The package may have incorrect main/module/exports
specified in its package.json: No known conditions for "." entry in "layercake" package
```

I managed to patch the error by re-writing the "exports" line in layercake's package.json file:

```json
"exports": {".": "./dist/index.js"},
```

However, I suspect this might break things for typescript users. Any ideas on a universal fix for this? Or perhaps something I could change in the config of my Svelte Kit project?

**Comment by mhkeller** [comment]
Thanks. Can you include some info on your build system and the versions you’re using?

**Comment by bothness** [comment]
Sure. I'm using the latest version of layercake (7.4.0).

This is what I get when I run `npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"` on the Svelte Kit project (I realise now that it's not the latest version of SK!):

```
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 1.11 GB / 7.72 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.43 => 1.0.0-next.43
    @sveltejs/kit: ^1.0.0-next.505 => 1.0.0-next.507
    svelte: ^3.50.1 => 3.58.0
    vite: ^3.1.4 => 3.1.4
```

**Comment by bothness** [comment]
Thanks Michael. It looks as though upgrading Vite and Svelte Kit to the latest versions has resolved this issue.
