### ISSUE TITLE
Upgrade to svelte 4

### ISSUE THREAD

**Issue by BioMatti** [mhkeller/layercake#136]
I upgraded to svelte 4 my project and I have seen that layercake requires svelte 3.

I tried to update your github repo by doing:

`pnpm up --latest`
`pnpm remove eslint-plugin-svelte3`
`pnpm i eslint-plugin-svelte`

After a ´pnpm build´ there are a lot of git changes in the docs folder. I'm not sure on how your repo is set up but probably those files are generated by svelte and now they look different because of svelte 4.

I have a fork here without the changes from `pnpm build`
https://github.com/MCMattia/layercake

**Comment by mhkeller** [comment]
This is pretty much done. Just want to coordinate the publish date with another project.
