### ISSUE TITLE
Create `cScale` for color?

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/layercake#138]
[@techniq](https://github.com/mhkeller/layercake/pull/121#issuecomment-1611622423):

> What do you think if we add a cScale or colorScale to LayerCake? I know any of the scales (x,y,z,r) can be used for color, but I think it could be helpful for reusable components to have a common scale used for color. I currently use the r scale in LayerChart (coloR) but there are cases where r overlaps with radius scales, for example. z can also overlap with faceted charts, or another dimension (stack/group/etc). I haven't looked deeply, but I know Plot has an explicit [color scale](https://observablehq.com/plot/features/scales#color-scales) (just called color).

That's an interesting idea. I use the `zScale` for color in the examples. How would you use it for faceting from within Layer Cake?

**Comment by techniq** [comment]
To be honest, I don't currently, but I've considered exploring, although the more I think about it, it's probably best to create new LayerCake instances as they would need individual scales/etc.  I know that's how the [Small multiples ](https://layercake.graphics/example/SmallMultiples)example works (with an opt-in shared scale).

I was going to investigate more how Plot does [facets](https://observablehq.com/plot/features/facets) / small multiples (they use `fx` and `fy` scales).  This is way down my priority list, I mostly mention that the `z` scale might be used for a third dimension (for example a multi-series line/area [chart](https://www.layerchart.com/docs/examples/Area#multiple-series) might use this approach, although I also just render separate explicit instances here).

**Comment by techniq** [comment]
Btw I was going to close this issue, but I don't have the permissions :)

**Comment by mhkeller** [comment]
In case you need another scale, you can create one yourself and pass it through the [`custom`](https://layercake.graphics/guide#custom) prop. I know you won't get automatic domain calculation but at least it gets you part of the way there in that you have a context value accessible from your chart components. 

I will probably hold off on adding a `cScale` for now. I want to square these existing issues and it may add overhead to the final compiled library. It may be too many options for people to learn. Sometimes constraints make things easier. 

But if you come across something where that fifth scale is really necessary, drop a comment and we'll check it out!
