### ISSUE TITLE
Option to use different canvas contexts?

### ISSUE THREAD

**Issue by dbaynard** [mhkeller/layercake#146]
The `Canvas` component by default sets the context to `2d`. This means the context cannot be changed later. Would you consider allowing this to be customized, perhaps as a prop on the `Canvas` component that defaults to `2d`?

https://github.com/mhkeller/layercake/blob/76b2d37aa151567e8573c40e39d9b590c75cfd81/src/lib/layouts/Canvas.svelte#L41

I'd be happy to make the PR.

With this, one can render using an `OffscreenCanvas` in a worker thread, and then transfer the `ImageBitmap` to the main thread. I haven't used this for charting, but I have hit this issue when trying to layer various components atop each other.

Edit: See [HTMLCanvasElement: getContext() method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext)

> Later calls to this method on the same canvas element, with the same `contextType` argument, will always return the same drawing context instance as was returned the first time the method was invoked. It is not possible to get a different drawing context object on a given canvas element.

**Comment by mhkeller** [comment]
Yea that seems like an easy thing to add. It’s also something that I would want people to know and understand when and how to use it. Would you be able to put together one or two examples showing what users would be able to do with this? 

Using the svelte REPL, you can easily copy the existing Canvas component and add this as a new prop.

**Comment by dbaynard** [comment]
Thanks. I've hit various issues when trying this, so I'll want to think about the design a little.

1.  Once can use [HTMLCanvasElement: transferControlToOffscreen() method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen) but only if there is _no_ context.
2.  `scaleCanvas` only works on a `CanvasRenderingContext2D`, and this is called in the existing component. I haven't worked through this, yet.

I'll think about examples; my only use case for the moment is rendering a canvas layer atop a video.

**Comment by mhkeller** [comment]
Got it. It may be that this is an entirely different component but the good news is there's nothing stopping someone from using the [existing canvas component](https://github.com/mhkeller/layercake/blob/main/src/lib/layouts/Canvas.svelte) as a base and simply loading that into their project

**Comment by mhkeller** [comment]
@dbaynard How's this going? Are you still working on this or should I close this issue for now? Always happy to re-open at a later date if you want to pick it back up then.

**Comment by dbaynard** [comment]
I'll re-open when I come back to this, or if there's interest from more folks.

**Comment by dbaynard** [comment]
(Changed how it is closed so as not to give an incorrect impression, and so I might be able to track it later…)
