### ISSUE TITLE
Ever expanding SVGs on deployed site

### ISSUE THREAD

**Issue by jurb** [mhkeller/layercake#18]
I'm trying to debug this but can't seem to figure it out.

I place my visualizations in several containers, using tailwind. There's a max-width in pixels on the main container, and I'm using 100% w/h for my chart containers.

Developing locally seems fine, but if I run `npm run build` and deploy my visualizations are expanding, forever.

![growingsvg](https://user-images.githubusercontent.com/913411/74931398-cf5ccf80-53df-11ea-8b0a-7f97eb7558fa.gif)

It's adding +1 to the svg height dynamically. I'm getting the 'Target div has a negative width' error in the console, but only in Safari.

Sorry about being vague, but I'm a bit stuck :)

**Comment by jurb** [comment]
Setting an absolute height on the container seems to fix the issue!

**Comment by jurb** [comment]
I'd love to find a way to make these charts 'really' responsive, however.

**Comment by mhkeller** [comment]
Interesting. What’s the container height? Can you reproduce it in the Svelte REPL?

--
@mhkeller
mhkeller.com

**Comment by mhkeller** [comment]
Can you still make a reproduction because the examples on the site are set to 100% height and they work fine. I'd like to figure out why this is happening.

**Comment by jurb** [comment]
I'll try to! I think the combination with tailwind is the culprit. I don't see how I would easily reproduce that in the repl and the repo I'm working in is private.

**Comment by mhkeller** [comment]
Hey @jurb, any progress on recreating the issue?
