### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by rgieseke** [mhkeller/layercake#211]
Finally following up on #191:

`npm run lint` currently reports

```
[warn] Code style issues found in 361 files. Run Prettier to fix.
```

`npm run check` gives

```
svelte-check found 954 errors and 24 warnings in 201 files
```

I would be very happy to help fixing these as I think it would be useful to have this reduced to more easily find issues related to a Svelte 5 transition.

It would be good to know your preferences, @mhkeller,  with regards to style guides etc as you wrote in https://github.com/mhkeller/layercake/pull/191#issuecomment-2096932854

Personally I'd go with whatever Svelte/Sveltekit defaults to as this makes it simple to put Layercake components into Sveltekit projects.

**Comment by mhkeller** [comment]
Yea that makes sense. Looking back through https://github.com/mhkeller/layercake/pull/191/files (I browsed about 20 percent so far), the changes seem fine. Adding parentheses around single arguments still feels verbose to me but maybe I'm the exception. Is that what everyone likes doing or Is there a way to change that rule?

**Comment by rgieseke** [comment]
> Adding parentheses around single arguments still feels verbose to me but maybe I'm the exception. Is that what everyone likes doing or Is there a way to change that rule?

Yes, there is `arrow-function-parenthses`.

https://prettier.io/docs/en/options.html#arrow-function-parentheses

I think the argument there - "However, when Prettier removes parentheses, it becomes harder to add type annotations, extra arguments or default values as well as making other changes" - could become relevant when more type annotations are added to Layer Cake.

Personally I'm totally fine to have whatever you prefer as it can be easily changed when e.g. a Layer Cake is dropped in another project. Just copying what Svelte/Kit does with regards to formatting could mean that it becomes a bit easier to track changes when you include a Layer Cake component in a Sveltekit project and later need to update it again.

**Comment by mhkeller** [comment]
@rgieseke take a look at that PR and see what you think. The only thing it's complaining about it is the brush component aria labels and I've opened this issue https://github.com/sveltejs/svelte/issues/12145

**Comment by mhkeller** [comment]
I've merged this for now but let me know of any thoughts.

**Comment by rgieseke** [comment]
That's fantastic, thank you!
