### ISSUE TITLE
`$domain` does not reflect `.nice()`

### ISSUE THREAD

**Issue by jnsprnw** [mhkeller/layercake#213]
Thanks so much for this great library! I use it nearly daily in my work.

I’m not sure if this is by design, but `$domain` does not reflect the extended domain when applying `.nice()` to the scale. Using `$yScale.domain()` in contrast returns the correct (extended) domain.

Here is an example of this behavior: https://svelte.dev/repl/cfbbdba51fa54921ae8a568b9e529576?version=4.2.18

In this example, the values differ like this:
```
$yDomain: [242.49063670412, 709.433333333333]
$yScale.domain(): [200, 750]
```

**Comment by mhkeller** [comment]
Hey @jnsprnw – I'm glad it's useful. Looks like you're doing neat work on climate issues. 

I think this is an oversight so thanks for bringing it to my attention. I think within [this if-block](https://github.com/mhkeller/layercake/blob/7ccd128ac3184322415f88974d5a184fdf0ba8fd/src/lib/helpers/createScale.js#L42), there should be a line like `$domain = scale.domain();`.
