### ISSUE TITLE
svelte-check error from svelte-app directory

### ISSUE THREAD

**Issue by rgieseke** [mhkeller/layercake#217]
When running `npm run check` I'm getting

```
> layercake@8.3.3 check
> svelte-kit sync && svelte-check --tsconfig ./jsconfig.json


====================================
Loading svelte-check in workspace: /home/robert/Code/layercake
Getting Svelte diagnostics...

Error while loading config at  /home/robert/Code/layercake/src/scripts/svelte-app/svelte.config.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/adapter-auto' imported from /home/robert/Code/layercake/src/scripts/svelte-app/svelte.config.js
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I couldn't figure out why `svelte-check` is trying to load the additional config file as the directory should be ignored from the `exlude` pattern in jsconfig.json.

https://github.com/mhkeller/layercake/blob/65011709df138a86085cab744b70c339402751bb/jsconfig.json#L26-L27

`adapter-auto` is not installed and installing `@sveltejs/adapter-auto` removes the error but I'm not sure that is the 'correct' solution.

As i understand the `update_template.sh` script is used to create the download button content, right?

**Comment by mhkeller** [comment]
Seems like Typescript `exclude` doesn't actually exclude things: https://github.com/Microsoft/TypeScript/issues/24133

**Comment by mhkeller** [comment]
You could do some workaround where you add a `// @ts-nocheck` when the template repo gets cloned and then remove it when the user downloads it but that seems like a lot of moving parts to satisfy the build tool. im kinda inclined to ignore this since.

**Comment by mhkeller** [comment]
Thanks for taking it on. Looks like a good workaround.
