### ISSUE TITLE
Tooltips on bar charts / d3-quadtree

### ISSUE THREAD

**Issue by jsfenfen** [mhkeller/layercake#22]
Do you have suggestions / an example for implementing tooltips on a bar chart? My naive attempts to do it with d3-quadtree are not immediately working, probably because I'm passing it the wrong things. For a bar chart with <50 bars I'm sorta tempted to rewrite QuadTree.svelte's [findItem](https://github.com/mhkeller/layercake-template/blob/master/src/components/QuadTree.svelte#L18), probably by ripping out d3-quadtree and replacing it with some elementary school math on the bar widths / heights. (the tear-it-down-and-replace-with-javascript-circa-1999 is an instinct I try to suppress, not always successfully).  I can start putting these issues on the examples repo too if that makes more sense to you. 

Unrelatedly I think I can contribute a HorizontalCategoricalMapScale component to the layer cake examples if that's at all useful, it's totally trivial to build, but the sorta thing that's handy to have all the same.

**Comment by jsfenfen** [comment]
Hmm, I guess functionally it's just easier to adapt the points example by adding bars.

**Comment by mhkeller** [comment]
Hey, ya the examples repo may make more sense. I'm in the process of making HTML versions of some of the components and in the process I want to document the different parameters a bit better. The d3-quadtree api can be a little abstract I agree. The tooltip example would also more accurately be a "shared tooltip" and I'd like to build hovers out on the other examples too. 

For the HorizontalCategoricalMapScale is that like a chloropleth map do you mean? Definitely put in a REPL link on an issue for the [layercake.graphics](https://github.com/mhkeller/layercake.graphics) repo. It may be good to create a README that links to the existing components and examples people have made, as well.
