### ISSUE TITLE
Add `repository` and `hompage` fields in `package.json`

### ISSUE THREAD

**Issue by Ennoriel** [mhkeller/layercake#245]
The Repository and Homepage (documentation website) links are not displayed on the npm page of layercake and hence not displayed on tools that use npm as a source of truth (for example: https://npmtrends.com).

I guess these are taken from the `repository` and `hompage` fields in `package.json`. You should probably add:

```json
  "homepage": "https://layercake.graphics/",
  "repository": {
    "type": "git",
    "url": "https://github.com/mhkeller/layercake"
  },
```

I know that at some point the Svelte core team used [publint](https://www.npmjs.com/package/publint) to check pagaging errors, but I'm not sure this would have resulted in a warning.

**Comment by mhkeller** [comment]
Thanks. Just added these in 8.4.1.
