### ISSUE TITLE
Examples Broken

### ISSUE THREAD

**Issue by iltimasd** [mhkeller/layercake#28]
Hi!

Just getting into Svelte and Layer Cake, but it seems all but 2 examples when opened in the REPL are broken?

The data gets drawn but there's no responsiveness

They all throw 
```
message: "Cannot read property 'defaultView' of null"
stack: TypeError: Cannot read property 'defaultView' of null
```

The only 2 that seem to still work are the circle packing examples.

Not sure if this is a problem with the REPL, or the library.

**Comment by iltimasd** [comment]
Hmm also looks like the SSR examples are still working (I've only check the Line+area example)?

Client side has no responsiveness, but SSR does. Both throw same error.

Client
https://svelte.dev/repl/ad32f9f301484d0cace82272126e9d09?version=3.17.3

SSR
https://svelte.dev/repl/ac23120460b1409a9e1e6fd328b63b64?version=3.17.3

**Comment by mhkeller** [comment]
That's unfortunately a limitation of how the REPL works. If you download the files from the REPL or from the website they should be responsive.

**Comment by mhkeller** [comment]
@iltimasd Let me know if those don't work for some reason! I'll close this issue for now since changing the REPL is out of scope.

**Comment by iltimasd** [comment]
Ahah! thank you for the clarification!

**Comment by mhkeller** [comment]
I think your experience is going to be pretty common so I went and added a note on all of the affected examples. Thanks for raising the issue! If you have any suggestions or see some without a note that aren't being responsive in the REPL, let me know!

Thanks again!
