### ISSUE TITLE
Layercake and Webcomponent

### ISSUE THREAD

**Issue by tettusud** [mhkeller/layercake#32]
How can I use Layercake in my Svelte , web component. ? If not tagged with options, compiler throws the error **Illegal Constructor**
For reference [https://github.com/sveltejs/svelte/issues/4132](https://github.com/sveltejs/svelte/issues/4132) [url edited by @mhkeller]

**Comment by mhkeller** [comment]
Can you post a reproduction repo. I haven't used a custom element before. If you could post a working version of a custom element and then the same code that breaks when you include layercake, that would be helpful to see if this is a problem with layercake or not.

**Comment by tettusud** [comment]
@mhkeller First of all Thanks a ton for your awesome work. 
And its not actually a problem with LayerCake alone, but with Svelte on a whole, Svelte expects each and every component to be tagged as custom element (including the imported/child component). So I was wondering if someone knows a way to work around, as Layercake is widely used.  

For example to expose any component (App.svelte)  as a web component , 
* we need to include the below tag in that component

`<svelte:options tag=”my-layercake-map” immutable={true} />`

* set **customElement:true** in rollup.config.js

and can use the component in any html just by using the tag `<my-layercake-map></my-layercake-map>`

But catch here is any sub component / any component that is imported  in my component  App.svelte, also need to have the tag included `<svelte:options tag=”my-child-component” immutable={true} />`

  I could not find a working solution, any fix is distorting maps/charts produced by LayerCake.

For reference [https://itnext.io/svelte-web-component-5-4kb-4afe46590d99](url)

**Comment by mhkeller** [comment]
Thanks that's very nice of you to say. If it's more of a Svelte issue then I don't think I'll be very helpful since I haven't worked with this feature. If you are able to put together a reproduction repo I could take a look in case there is something about LayerCake that I see that would point you in the right direction. Understanding how the maps and charts are distorted may offer a clue.

**Comment by mhkeller** [comment]
One thing to keep in mind is that LayerCake is just a regular svelte component. You could paste the `src` folder into your project and import the components directly instead of having them be exported from [index.js](https://github.com/mhkeller/layercake/blob/master/src/index.js). If your chart components are appearing but aren't sized propertly, it may have something to do with the width and height not being reactive once it's built into that environment.

**Comment by tettusud** [comment]
@mhkeller  agreed its a regular svelte component, but a regular svelte component can not be used as part of web component (neither as part of the same project or imported regular component from external library)
Here you go sample project https://github.com/tettusud/svelte-wc-layercake
It has 3 branches
1. **master** has  working fine version of a map built using layercake .
2. **working-web-componet** is a simple hello world component, built as web-component
3. **layercake-webcompone-workaround** , a work around to exclude layercomponent module from being built as web component , here map zooms/moves automatically.
4. **compilation-errors-bcoz-of-missing-tags** ,without workaround build will not succeed because imported modules (ie layercake) are not web components.
Apologies have not gone through deeper why it behaves that way.

**Comment by tettusud** [comment]
@mhkeller  am closing this issue. I found an alternate way to achieve what I wanted. Once again kudos for your time and effort.

**Comment by mhkeller** [comment]
If you think your solution will help other people, feel free to drop a link to an example of what you've put together.

**Comment by chewbakartik** [comment]
@tettusud would you be willing to share what your workaround for this issue? I'm running into a similar problem importing a different library into a custom web component and am completely at a loss for how I can move forward past this.

**Comment by tettusud** [comment]
Actually I reverted to the normal svelte component, and am handling it like this in main.ts
```
import App from './App.svelte';
// get elements
const elements = document.getElementsByTagName("custom-component");
const targets = Array.from(elements);
var apps = [];
if (targets) {
	apps = targets.map(target => new App({
		target, props: {
			src: target.getAttribute("src")
		}
	}))
}
export default apps;
```

**Comment by ncbot-lk** [comment]
> Actually I reverted to the normal svelte component, and am handling it like this in main.ts ,not sure of the consequences though.
> 
> ```
> import App from './App.svelte';
> // get elements
> const elements = document.getElementsByTagName("custom-component");
> const targets = Array.from(elements);
> var apps = [];
> if (targets) {
> 	apps = targets.map(target => new App({
> 		target, props: {
> 			src: target.getAttribute("src")
> 		}
> 	}))
> }
> export default apps;
> ```
> 
> And you can use custom-component tag in the html

It does work, but feels like a hacky way to achieve a custom tag but the context is not isolated under a shadow-dom anymore
