### ISSUE TITLE
file system: move utils/* and helpers/* to lib/

### ISSUE THREAD

**Issue by milahu** [mhkeller/layercake#39]
.. to make it easier to find source files

**Comment by mhkeller** [comment]
What problem did you run into? I organized it so that the file in `lib/` were the functions exported by the library, as opposed to more internal functions.

**Comment by mhkeller** [comment]
I'm going to close this for now since it purely applies to how the library's internal organizational structure. If you have more thoughts on why these files should be in different folders and what issues that would solve, feel free to reopen.
