### ISSUE TITLE
Multipanel?

### ISSUE THREAD

**Issue by zahachtah** [mhkeller/layercake#43]
Hi, I am exploring how to best make multi-panel figures. I see you have one small multiple, but I want something that has much more freedom in placement than css grids. 

I would want a main plotting area and then put Layercake graphs at certain coordinates (so you can recreated grids, but you can also just have e.g. the small multiples arranged in a circle. 

I tried moving the graphs with xrange/yrange but Layercake seem to still consider the whole area as its playground and one can't have two Layercakes in one div? (terrible example [here](https://svelte.dev/repl/65280116e99a4173ace84dfe981c8fa3?version=3.17.3))

Do you have any hints how to achieve this, e.g. multiple graphs with separate coordinate systems within one svg? Or would I have to use one coordinate system from layer cake and then mak my own component to translate figure coordinates within that?

May be a LayerGroup component with translated coordinates and position in which one use the visualisation components...just a thought

**Comment by mhkeller** [comment]
HI @zahachtah, I had played around with having a concept of "regions" within each `<LayerCake>` component where you could assign a group of layers to an area but it got very complicated and, in the end, was largely just replicating a lot of basic HTML functionality. So, the library has landed on a one-div–one-layercake model and you can't have multiple coordinate systems. 

What are you running into where it seems better to have multiple coordinate systems inside one svg instead of arranging different `<LayerCake>` components in a parent div with CSS grid areas?

**Comment by mhkeller** [comment]
[edited the above comment to clarify the css grid structure]

**Comment by mhkeller** [comment]
Hi @zahachtah I'm going to close this issue since the underlying question has been addressed. If you want to chat about any limitations you're running into, though, feel free to keep posting here.

**Comment by zahachtah** [comment]
yes, thank you! sorry for not responding immediately. 

Its just that in general making multipanel figures one very quickly gets into issues when one wants to have e.g. y-axis only on the leftmost, or legends spanning only parts of the panels. I realise its possible to address that with clever code, but I also wanted to try to break away from the rigid grid-thinking, e.g. when one wants to have an illustration mixed with interactive graphs and where the graphs can be placed anywhere. I'll ponder this a bit and maybe just take inspiration from layer cake and try something myself. Thanks for this anyway, enjoy playing with it and learned a lot.

**Comment by zahachtah** [comment]
I have ended up just using a wrapper div with position:relatiev and then have multiple container divs for the Layercake graphs positioning them by position:absolute; This works nicely and I can make any type of layouts. My initial issue was that I possibly want to save everything as one svg file but I realised I can just add all svg's int he download function into one and position them in groups. So this seems a great solution.

Another question is wether it might be useful to have <SVG/> <Canvas/><Html/> etc also export a context letting their children know what they are in. This is so one could make one single <Point/> component that will render differently wether its in a canvas or svg. One nice advantage would be that you could make a scatterplot using svg, but one day you throw a lot more points at it and you can just switch it to canvas (or even webgl) without changing the code. May be you don't want to add "features" and keep it as lean and possible, I can certainly add this feature myself. Its fun playing with it!

**Comment by mhkeller** [comment]
@zahachtah that's an interesting idea. Maybe it would be `const { type } = getContext('layout')`.

I would probably structure the components slightly differently with that approach. I would make one `PointsWrapper` component that rendered the SVG or Canvas `Point` component based on the context variable. That way, the `PointsWrapper` component is an abstraction that covers both separate renderers. Let me know if you continue with this or you find other use cases for knowing what kind of layout the renderer is in. At the moment, you could easily accomplish this by passing a `type`prop to your component so there's nothing blocking you from doing this, but I could see how it would save a prop if it was already for free in the context.
