### ISSUE TITLE
Replace quadratic-time algorithm for uniques()?

### ISSUE THREAD

**Issue by jtrim-ons** [mhkeller/layercake#46]
The uniques() function checks if each item is in an array of seen items, which I think leads to quadratic complexity overall. There are probably use cases such as a scatter plot with thousands of points where this would take a noticeable length of time.

Would it be worth making `seen` a `Set`? I think it would just need the following changes:

- `const seen = [];` -> `const seen = new Set();`
- `seen.includes(computed)` -> `seen.has(computed)`
- `seen.push(computed)` -> `seen.add(computed)`

**Comment by mhkeller** [comment]
Ah very good idea! This function was a holdover from another era.

**Comment by jtrim-ons** [comment]
Great - I'll have a go at a PR just now.

**Comment by mhkeller** [comment]
Thanks for jumping in! I'll take a look!

**Comment by mhkeller** [comment]
Sorry for the delay! This is now published as v4.1.1! Thanks again! I'll hopefully get some time in the coming two weeks to go over the calcExtents API change, too.
