### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by abalmos** [mhkeller/layercake#49]
Sorry if this is the wrong place to ask, but don't see any other community forum/chat.

I just wanted to verify that I am not missing user contributed Typescript types for Layer Cake that you might be aware of?

**Comment by mhkeller** [comment]
There aren’t but I should add them. Do you have an example repo that implements them?

**Comment by abalmos** [comment]
I don't yet, but I have considered starting a set. Unfortunately, at the moment I don't have the free time to spare. Maybe soon -- thanks for confirming.

**Comment by abalmos** [comment]
Are you open to converting the code base to TS? Looking at the source, I'm wondering if that isn't too much more work then creating a .d.ts file.

**Comment by mhkeller** [comment]
Yeah I think it's a good idea – I just want to see how other svelte projects have implemented them / best practices etc.

**Comment by mhkeller** [comment]
I'm tinkering with the best way to do this on the [kit](https://github.com/mhkeller/layercake/blob/kit/src/lib/LayerCake.svelte) branch. I'm finding a lack of great docs and examples, though so if anyone has any ideas on best practices, please let me know.

**Comment by pierreminik** [comment]
I add my interfaces and types in the `src/global.s.ts` (without `export`) and then I don’t need to import them anywhere. I don’t know if this is best practise but it seems to work okay.

**Comment by mhkeller** [comment]
The kit branch now has these if anyone wants to test: https://github.com/mhkeller/layercake/tree/kit

**Comment by mhkeller** [comment]
I'm going to close these in favor of this issue: https://github.com/mhkeller/layercake/issues/56 any testing would still be appreciated!

**Comment by abalmos** [comment]
@mhkeller Thanks for looking at this. I had to walk away from that project for a little while but I hope to get back to it by latest early next week. I will try out #56 and give feed/help as needed when I do so if the PR is still open.

In the meantime I had gone the same route as @pierreminik and built my own `types.d.ts` but your approach in #56 is much better long term.
