### ISSUE TITLE
SvelteKit 1.0.0-next.202 / Vite 2.7 issue

### ISSUE THREAD

**Issue by techniq** [mhkeller/layercake#54]
After upgrading to SvelteKit `1.0.0-next.202` which [includes Vite 2.7](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next202), I receive the following when importing LayerCake:

```
10:36:36 PM [vite] Error when evaluating SSR module /src/lib/components/Chart.svelte:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /Users/techniq/Documents/Development/open-source/layerchart/node_modules/layercake/src/LayerCake.svelte
    at new NodeError (node:internal/errors:371:5)
    at Object.file: (node:internal/modules/esm/get_format:72:15)
    at defaultGetFormat (node:internal/modules/esm/get_format:85:38)
    at defaultLoad (node:internal/modules/esm/load:13:42)
    at ESMLoader.load (node:internal/modules/esm/loader:303:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:230:58)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:244:11)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:78:21)
    at async Promise.all (index 0)
```

While I'm not 100% certain, I believe the heuristic changed with Vite 2.7 to detect a svelte package, and the best tell now is to include a `svelte` property in `package.json` (along with `main`/`exports`).  If using SvelteKit to build packages, running `svelte-kit package` [now](https://github.com/sveltejs/kit/pull/2431) sets this for you.  This PR along with the associated [issue](https://github.com/sveltejs/kit/issues/1959) and [code](https://github.com/sveltejs/kit/blob/master/packages/kit/src/packaging/index.js#L120-L145) provides some additional info.

Sending a PR your way...

**Comment by mhkeller** [comment]
Interestingly, I get this same error when using the new sveltekit version even though it has `"svelte": "./index.js"` in its package.json. I think I have to do some more configuration around exports though because it's currently exporting too much.

**Comment by techniq** [comment]
Hmm. It’s currently working for me and published/deployed an update to LayerChart with it. I know on my primary application I had layercake in optimizeDeps within svelte.config.js which was still giving me the error (or similar) until I removed it, although I don’t see that in your kit branch at all.

I was just calling it a night (typing on my phone) but if you’re still having issues I can take a look tomorrow sometime.

**Comment by mhkeller** [comment]
Nope not urgent and it seems to be working now. My next step is to see if it works with the layercake.graphics examples but that will be for another day.
