### ISSUE TITLE
Rename `flatData` -> `dataForExtents`?

### ISSUE THREAD

**Issue by mhkeller** [mhkeller/layercake#57]
Per, https://github.com/mhkeller/layercake/issues/53#issuecomment-997440185, would it make more sense to rename the `flatData` to `dataForExtents`? It speaks more to what it's used for, which is a little less mysterious than describing what it must be.

This would be a breaking change but we can still support `flatData` for a little bit so things wouldn't actually break. I'm just about ready to publish version 6.0.0, which is the svelte-kit version. There are no other changes though – just figured it would be good to bump the major version in case it breaks a build process or something.

**Comment by techniq** [comment]
I like the explicitness, although I have used `flatData` in other contexts beyond extents within [LayerChart](https://github.com/techniq/layerchart/search?q=flatdata) / my projects.  It's useful to know you have long vs wide data in those contexts like Tooltips (there might also be some opportunity to use $data vs $flatData though).

I would need to refactor my use of flatData if so.  I kind of prefer how it is now, but also understand the potential confusion and would be fine with the change either way.

**Comment by albertsun** [comment]
`flatData` feels better to me I think, it's the `data` but passed through `flatten` or something like that. And while it's used for extents it could _also_ be used for other things, whereas if it were called `dataForExtents` it might suggest that it's an array with _just_ the four min/max points.

**Comment by mhkeller** [comment]
Good points @techniq and @albertsun! Let's keep `flatData`! Thanks for weighing in!
