### ISSUE TITLE
Maybe provide a "main", not just a "module"

### ISSUE THREAD

**Issue by zzolo** [mhkeller/layercake#6]
[`esm` doesn't seem to work with this module](https://github.com/standard-things/esm/issues/693).

This looks like it may be a bug or I may just have something way off, but it might be useful to provide a `main` field, and not just a `module` field.

And it might be worth updating the documentation that the module is only provided in ES module syntax.

Thanks for the help and great library.

**Comment by mhkeller** [comment]
I'll add that and push a patch version to see if it fixes things for you. I wonder if the [svelte-component](https://github.com/sveltejs/component-template) setup is the right way to compile it. What is your environment you're using it in?

**Comment by mhkeller** [comment]
0.3.1 has the main field!

**Comment by zzolo** [comment]
Awesome!  This worked for me well.
