### ISSUE TITLE
on:blur click events create an outline around svg paths

### ISSUE THREAD

**Issue by philipmnelson** [mhkeller/layercake#63]
I noticed that adding an on:blur event handler creates an outline around the focused element, this results in strange behavior when clicking a path. See examples below:

* non-SSR version
 ![example of non-ssr version](https://user-images.githubusercontent.com/12937257/152659099-f42a178a-768f-46c0-8bfb-3b2e4b773916.gif)
* SSR version
![example of ssr version](https://user-images.githubusercontent.com/12937257/152659454-0582c041-4d5a-4f95-8ad0-92d7b7e21a7a.gif)

To fix this issue on the Map component, I just added `
.feature-path:focus {
		outline: none;
	}` to the <style/> block in the map component.
After reading through  [:focus' MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus), I'm not sure this is the best or most accessible solution. Thoughts? I'm happy to work on implementing a fix but I'm not entirely sure what the most accessible solution is.

**Comment by mhkeller** [comment]
Thanks for investigating this! I've added this CSS rule and a comment linking here and to the MDN article. Closed via https://github.com/mhkeller/layercake/commit/3df4b383658ae9827a5f1e4f4913c394a58c67f7
