### ISSUE TITLE
sveltekit adapter static cannot build, npm run dev works fine

### ISSUE THREAD

**Issue by x4080** [mhkeller/layercake#64]
Hi,

the error I got is 
```
> Using @sveltejs/adapter-static
TypeError: Cannot destructure property 'width' of 'getContext(...)' as it is undefined.
    at file:///D:/sveltekit%20projects/capacitor/.svelte-kit/output/server/entries/pages/layercake/AxisX.svelte
...
```

I rename the component folder to layercake and put it inside route, npm run dev works fine, I thought the problem is getContext but I tried using other component that use getContext and build normally, any tips ?

Thanks

**Comment by mhkeller** [comment]
Hi @x4080, Hm strange. Can you create a simple reproduction repository and I'll check it out?

**Comment by x4080** [comment]
@mhkeller Thanks for quick response, I tried again using empty sveltekit project and still wont work, I created this git if you kindly want to check it out :
https://github.com/x4080/layercake

**Comment by mhkeller** [comment]
I think the issue is putting your components inside of the `routes/` folder. I put the `layercake` folder as a sibling of `routes/` inside of `src/` and both `npm run dev` and `npm run build` work fine.

**Comment by mhkeller** [comment]
Or, you could prefix `layercake` with an underscore (`_layercake`) so that it's ignored as a route. The issue, I believe, is that it's trying to be built as a page endpoint.

**Comment by x4080** [comment]
@mhkeller Thanks, I'll try it and let you know

**Comment by x4080** [comment]
Yes, it works - thanks
