### ISSUE TITLE
500 error in component docs

### ISSUE THREAD

**Issue by jwilber** [mhkeller/layercake#65]
Great resource!

Looks like a recent update may have messed up some links required for documentation!

E.g., clicking on any of the chart thumbnails from [https://layercake.graphics/components](https://layercake.graphics/components) yields the following error:

500
Failed to fetch dynamically imported module: https://layercake.graphics/_app/pages/components/_slug_.svelte-998c6316.js
TypeError: Failed to fetch dynamically imported module: https://layercake.graphics/_app/pages/components/_slug_.svelte-998c6316.js

**Comment by mhkeller** [comment]
Hm weird, those pages load fine for me. I was doing some work on the site last night, though. Could you try clearing your cache or trying in a different browser? I wonder if a cached version of the page is trying to load a javascript resource that was overwritten by the new build that I pushed yesterday.

**Comment by jwilber** [comment]
A cache error indeed!

**Comment by mhkeller** [comment]
No problem – thanks for the repeat visit!
