### ISSUE TITLE
Small Multiples not showing up in Safari

### ISSUE THREAD

**Issue by dahilzen** [mhkeller/layercake#69]
I unfortunately stumbled upon another error. In Safari, some small multiples are not displayed. According to the console, width and height are not defined, but this is not true. The error only occurs in Safari and on iPhone browsers. Android and other desktop browsers display everything correctly.

I have put my code in a REPL.  https://svelte.dev/repl/15323c601e224a8d8753d5ead7c153af?version=3.46.4

Also, in this REPL you can see the width/height-error we talked about in #67

**Comment by dahilzen** [comment]
Here is an image. Besides the first one all SVG have width="0" and height="0"

![image](https://user-images.githubusercontent.com/16721203/154983400-133ca0b1-5204-4376-977d-cdd058201fe0.png)

**Comment by dahilzen** [comment]
The same chart in Chrome on Windows

![image](https://user-images.githubusercontent.com/16721203/154984542-4cf89d51-2150-4ad6-ae50-4aae32c0877a.png)

**Comment by dahilzen** [comment]
I worked around this by keeping track wether the component has mounted like you did in the reactivity branch.

```
let isMounted = false;
onMount(() => {
    isMounted = true;
});
```
 and later

```
<div style="height:200px;width:100%">
{#if isMounted}
  <LayerCake>
     foo
  </LayerCake>
{/if}
</div>
```

Seems like the SVG is build before the div-container are available.

**Comment by mhkeller** [comment]
Hm, this is what I see in Safari 15.3 (17612.4.9.1.5
<img width="1278" alt="Screen Shot 2022-02-22 at 11 07 05 AM" src="https://user-images.githubusercontent.com/498744/155171763-8eeb7f80-2fc3-4484-943b-249cd0820b8e.png">
)

**Comment by mhkeller** [comment]
and this is what I see on Safari on iOS. I’m not seeing this error hmm

![0F56E7EF-4745-46D2-8D17-74F11D0F6F0B](https://user-images.githubusercontent.com/498744/155172400-ae4085d1-fa34-47cd-bf8a-8dcb400d62bc.png)

**Comment by mhkeller** [comment]
Hey @dahilzen, let me know what the status of this is. I wasn't able to reproduce it.

**Comment by dahilzen** [comment]
Hi, sorry for the late response. I am not sure about it, maybe it has something to do with the CMS or the main.css of the site I am embedding the charts. I will take a further look into it, but i guess it is not a general problem. And the workaround above does its job. ____________________David Hilzendegen Eichendorffstraße 678234 ***@***.***: +49 151 5481 7835Am 27.02.2022 23:02 schrieb Michael Keller ***@***.***>:
Hey @dahilzen, let me know what the status of this is. I wasn't able to reproduce it.

**Comment by mhkeller** [comment]
Okay let me know if you end up figuring out what the issue is!
