### ISSUE TITLE
Examples dropdown list is broken

### ISSUE THREAD

**Issue by joshrayman** [mhkeller/layercake#70]
Hello,

Noticed the dropdown for looking at examples now sends you to lowercase versions of the pages which don't load. If you navigate via the components it sends you to the correct link for the examples.

It's this line, but I couldn't see where it was being generated, otherwise I'd have opened a PR.

https://github.com/mhkeller/layercake/blob/main/docs/index.html#L24

Thanks,

**Comment by mhkeller** [comment]
Thanks for the catch. It was [this commit](https://github.com/mhkeller/layercake/commit/a0b1d459dcf61f30ed41d420109d8eaeba56bc96) and looks like it needs some more testing to make it work. I've reverted it for now so if you clear your cache and refresh it should be working https://github.com/mhkeller/layercake/commit/7de21db1137108a6d290bd1eca9356f043371df9
