### ISSUE TITLE
How to zoom in/out a circle in CirclePack?

### ISSUE THREAD

**Issue by renatocaliari** [mhkeller/layercake#75]
I'd like to zoom in a circle when clicking on it and zoom out if clicked again.
In D3 it's possible doing "zoomable" circles: https://observablehq.com/@d3/zoomable-circle-packing.

Does someone know how to do it?

Thanks.

**Comment by mhkeller** [comment]
Hi @renatocaliari I'd have to study that example to understand well how it works and how best to convert it to svelte. It's doing a lot of fancy things using D3 transitions. I think the bulk of the work would be finding svelte equivalents for the tween and transition as opposed to layercake equivalents, if that makes sense? 

If you're fine with it not being super svelte-y, you could probably just copy the `zoom` and `zoomTo` functions and create the D3 selection references to `label` and `node` inside of an `onMount`.

**Comment by renatocaliari** [comment]
Thanks @mhkeller. 

At the moment it would be ok for me to mix a little more of the D3 library to get this done.
Just before posting this topic I had quickly tried to do something with zoom and zoomTo but without success.

Certainly, my lack of experience with D3 contributed. :)

**Comment by mhkeller** [comment]
I'm going to close this issue since it's not so much related to this library but how to implement a d3 zoom in svelte. Let me know if you end up posting an example that would be helpful for others to see.

**Comment by karlhayek** [comment]
@renatocaliari did you manage to implement a zoom in/out in a CirclePack ? I'm new to D3 and would gladly use some help !
