### ISSUE TITLE
Line + Area example AxisX.svelte component strange label behaviour when snapTicks is set to true

### ISSUE THREAD

**Issue by PlkMarudny** [mhkeller/layercake#78]
No directly related to the library itself maybe, but if you take a look at this [REPL](https://svelte.dev/repl/0eb41737a2d54f8498d8606bd2b6b22d?version=3.48.0), the last and the previous labels have the ```textAnchor``` attribute set to ```end``` when the component property ```snapTicks``` is set to ```true```. Somehow this function fails:
```
function textAnchor(i) {
		if (snapTicks === true) {
			if (i === 0) {
				return 'start';
			}
			if (i === tickVals.length - 1) {
				return 'end';
			}
		}
		return 'middle';
	}
```

**Comment by mhkeller** [comment]
Here's a [REPL](https://svelte.dev/repl/8e30785b6a544e9f96e8bb0d2be20110?version=3.48.0) with the fix

**Comment by PlkMarudny** [comment]
Indeed this is it, thank you.
