### ISSUE TITLE
Consider not reversing yScale by default for scaleBand

### ISSUE THREAD

**Issue by techniq** [mhkeller/layercake#83]
[Currently](https://github.com/mhkeller/layercake/blob/main/src/lib/settings/defaultReverses.js#L3) the yRange is always [reversed](https://layercake.graphics/guide#yreverse), but this can lead to some unexpected results when using `scaleBand` as the defined `yDomain` order not being maintained (rendered bottom up instead of top down).  For example:

- https://layercake.graphics/example/Bar/
- https://layercake.graphics/example/BarStacked/
- https://layercake.graphics/example/ClevelandDotPlot

You can work around this two different ways:
- Reverse the domain passed, as done in this example: https://layercake.graphics/example/Timeplot/
- Set `yReverse={false}`

The former is what I've been doing (mostly out of trial/error), although it has caused me other issues when things expect a certain order, like bisecting or [inverting a scaleBand](https://github.com/techniq/layerchart/blob/master/src/lib/utils/scales.ts#L5-L23).

While there is typically not a great way to identify the type of scale, luckily scaleBand (and scalePoint) can be identified by checking the present of `scale.bandwidth` which I do in [LayerChart](https://github.com/techniq/layerchart/blob/master/src/lib/utils/scales.ts#L27-L29) quite often.

I might change how I handle `yReverse` in LayerChart to accommodate this, but wanted to run it by you first, as I try not to deviate too much :).  I do have a [Chart](https://github.com/techniq/layerchart/blob/master/src/lib/components/Chart.svelte) component that provides a few conveniences , some of which might be worth moving up to LayerCake.

**Comment by mhkeller** [comment]
Hey thanks for this. Would using the yReverse option fix those secondary issues you’re seeing when reversing the order. 

This is for sure a tough one. Here’s a summary of the thinking that led to this: I decided to make the reverse be the default since it makes getting up and running much easier. From there, it seemed good to just keep things consistent and not have dynamic properties, I.e. the value of yReverse defaulting to false for bandwidth scales.

However, that could be a consideration more in the abstract sense of the library and users would generally prefer to just have as many chart types work out of the box as possible. 

Curious to hear any other thoughts but this seems like a reasonable change. Are there any scenarios where the changing nature of yReverse is problematic?

**Comment by techniq** [comment]
I just really just discovered `yReverse` today as a solution.  Let me test things out a bit more (currently updating [LayerChart](https://github.com/techniq/layerchart/issues/29) to better support this).  I was curious if you had any initial thoughts on where it might fall short.  It's interesting a lot of the examples I find on observable/etc have this characteristic of showing the values bottom up.

I need to run out for a bit (cut grass and food), but should be able to finish this up tonight, and I'll let you know if I find any downsides.

**Comment by techniq** [comment]
@mhkeller So far my initial tests have gone well, fixing top-down display without extra complexity, and has allowed me to implement `bisect-band` [Tooltip](https://layerchart.vercel.app/components/Tooltip) mode since the domain is not reversed.  This mode is useful for "multiple (overlapping) Durations" for example.

I've updated LayerChart's `Chart` component to default [yReverse](https://github.com/techniq/layerchart/commit/cfa11b0f62a91729ce45c3256223022c8e68e2ab) based on if it's scaleBand or not.  If you do add this to LayerCake, I'll remove my logic to reduce complexity / chance for inconsistencies.

**Comment by mhkeller** [comment]
Could you work on a PR for how this would work in layer cake?

**Comment by techniq** [comment]
With the abstractions/helpers you have to build the default ranges and
such, it looked fairly deep reaching… I can still PR, but not sure when I’d
get around to it.

The change in LayerChart was very simple, but mostly because it sits above
LayerCake :)

I’m OK to keep this in LayerChart only for now, but also don’t mind working
up a PR. I’m on vacation starting tomorrow so will likely be a few weeks.

**Comment by techniq** [comment]
Actually it might not be as bad as I originally thought.  I'll send over a rough PR to discuss

**Comment by mhkeller** [comment]
The more I think about this it seems more reasonable to have yReverse be dependent on the scale type. The ultimate goal is to have nice looking charts and people likely aren't digging into the details of all the default props

**Comment by mhkeller** [comment]
This is an old issue that would work well in conjunction with this one: https://github.com/mhkeller/layercake/issues/27

**Comment by mhkeller** [comment]
This is added in v7.0
