### ISSUE TITLE
Domain not dynamic enough, allow mapping function in domain

### ISSUE THREAD

**Issue by tylkomat** [mhkeller/layercake#87]
It would be good if domain would also accept a mapping function to be able to calculate min and max based on context like with the values x,y,z,r.

I would like to have a grouped bar diagram, like shown here:
https://svelte.dev/repl/d5d3eef9aa9a42e4b07c0a3b917a3242?version=3.17.3

But in my case the different bars (in the example data, apples, bananas, cherries and dates) are not in the same domain, they are independent of each other. I would like to be able to calculate [min, max] for apples, another one for bananas and so on.

If this is achievable with the current version, I would be happy for a hint.

**Comment by mhkeller** [comment]
The way to do this currently is to pass in a flat copy of your data that Layer Cake can loop through to calculate the extents. Here's an example: https://svelte.dev/repl/5a691c524ca440629e17c63a8063f9c8?version=3.17.3

Set `yDomain={[0, null]}` to ensure your chart starts at 0 and the `null` will adjust to the dynamic value of the max element in your dataset.

What's the alternative syntax you're suggesting? Something like this:

```svelte
yDomain={[0, data => max(data.flatMap(d => d.values).map(d => d.value)]}
```

**Comment by mhkeller** [comment]
Based on this example, I'm not sure what advantage specifying the max inside of the `yDomain` prop gets you as opposed to calculating it outside of Layer Cake. If the argument passed into it were also dynamic I could see an argument for it but the domain is global or the whole "cake" so you would just be setting it to one value anyway – no need for dynamic mapping. 

Maybe if you're calling this inside of a loop you could have dynamic extents but you could solve that either through the `flatData` prop or if for some reason you didn't want to do that, assigning the max to a local variable using svelte's `@const` syntax inside of a loop. Let me know if I'm missing some scenario that currently be accomplished one of these two ways or they are deficient in some way I'm not seeing.

**Comment by tylkomat** [comment]
This is what I trying to create:
![image](https://user-images.githubusercontent.com/815915/176945620-02b1eca3-9e92-4f3e-884a-29d168a9c164.png)

The bars with the same color share the maximum (domain) and each different color also has a different maximum value. The yellow bar is time in seconds, it could even go up to 30 minutes which is 1800 seconds. The other bars are percentages and only go until 100. With a global domain all bars are displayed relative to the 1800 in length, which makes them tiny, although reaching 100% should be a full bar as well.

**Comment by mhkeller** [comment]
if the units are different, I would do those as three different charts in a loop

**Comment by mhkeller** [comment]
{#each datasets as data}
  <div class="chart-container">
     <LayerCake...>
  </div>
{/each}

**Comment by tylkomat** [comment]
Thanks for the hint. I looking to have everything as a single SVG, but making each bar separate is much more simple.
