### ISSUE TITLE
Multiline with separate scales

### ISSUE THREAD

**Issue by weeblr** [mhkeller/layercake#96]
Hi

I am trying to represent a set of data (4 series) using a Multiline. It's kinda working using the [Multiline example](https://layercake.graphics/example/MultiLine) in the documentation except for one thing: the Multiline example assumes all series have the same scale.

In my case, I want to draw 4 series with vastly different scales ( series A: 0-100, series B: 0-10,000 or more, series C: 0-100,...). As the same scale is used for all series, series B is properly represented but all other are just a line on horizontal axis.

I could not find a way to properly handle this within LayerCake. Am I missing something?

NB: I tried superposing multiple <Layercake/> components, each drawing a single line, works fine but then sharedtooltip to show all 4 numerical values seems broken when I do that.

I'm thinking about  massaging the data before supplying it to LayerCake to re-scale it but then the values displayed by the Tooltip would be off

How would you advise to go about this?

Many thanks!

**Comment by mhkeller** [comment]
I would go the super imposition route — one LayerCake per series with a different scale — and then have an additional LayerCake component on top that’s just for the shared tooltip that has all the data.

**Comment by weeblr** [comment]
Thanks for your reply. I went that way already (had quite some trouble figuring out the data format for the Tooltips but working now). 

Was hoping this would be handled natively. 

Doing this, I had not modify the `formatValue `function signature in `SharedTooltip.html` to also pass the `row.key`. With only the row value, it's not possible to format the value, you need to know wich series you're formatting (one is a percentage, one is click count, etc).

**Comment by mhkeller** [comment]
Makes sense. I'm glad you were able to get it working

> Was hoping this would be handled natively.

One of the core ideas with Layer Cake is each `<LayerCake>` component really only handles one unit of data. The "native" way to handle your use case is to do the stacking technique so that the coordinate spaces are synced but each data is handled by its own scales.

**Comment by weeblr** [comment]
Hi 

I had seen that but didn't grasp at first that it would be a general thing to do, especially considering the "Multiline" example, which seems to hint this is possible.

Stacking context does lead to the same data being reprocessed (each individual LineD3 in my case, plus the SharedTooltips) but I guess that's not a major isssue, nothing that can be noticed.

So the 2 remarks I have after doing this are:

- when formatting the SharedTooltip (formatTick), passing the key on top of the value is nice, as it allows sharing the formatting function between 

- when drawing lines or lineD3, it'd be nice to have a stroke-dasharray property on top of the strokecolor. For accessibility, multiple lines on the same drawing should not rely on color only to be distinguished. Being able to pass a dasharray allows drawing lines that can more easily be visually identified

![image](https://user-images.githubusercontent.com/5846185/184111858-33148203-5067-4b32-8f25-0c3285f874d1.png)


I know all this is related to the examples, not to LayerCake core, but may be something to consider updating for the examples as surely they serve as a reference for many.


Cheers
