### ISSUE TITLE
<a> elements in <LayerCake> <Svg > are invisible

### ISSUE THREAD

**Issue by jackc** [mhkeller/layercake#97]
I was trying to port a hand built visualization to use layercake and I had great difficulty getting it to appear.

Almost every part of my visualization is a link. I was finally able to determine that anything inside of an `<a>` element is invisible. Presumably this is caused by a style in the wrapping containers created by `<LayerCake>` or `<Svg>` but I was unable to determine what or how.

This can easily be duplicated on https://github.com/mhkeller/layercake-template by changing `Area.svelte` to wrap the `path` with a `a`.

```
<a href="/foo">
<path class='path-area' d='{area}' {fill}></path>
</a>
```

The area fill disappears. I've also tried it with `<line>` and `<rect>` and those disappear as well.

**Comment by mhkeller** [comment]
Hm how weird. If I paste the generated svg into a svelte repl it displays properly https://svelte.dev/repl/hello-world?version=3.49.0

So there's nothing wrong with how the svg is being generated. I wonder if this is a svelte bug possibly related to this: https://github.com/mhkeller/layercake/issues/76

**Comment by mhkeller** [comment]
I replicated this without using layercake. The problem it seems is a svelte bug that doesn't render the `<a>` elements when passing items to another component via a slot prop: https://svelte.dev/repl/08270639a2154ea18192cbdf30861da8?version=3.49.0

Tracking here: https://github.com/sveltejs/svelte/issues/7807

**Comment by jackc** [comment]
Wow, that's tricky. Thanks for looking into it.

**Comment by jackc** [comment]
Thanks to the info in those issues you linked to I thought to try explicitly setting `xmlns` on the `a` element.

```
<a href="/foo" xmlns="http://www.w3.org/2000/svg">
<path class='path-area' d='{area}' {fill}></path>
</a>
```

...and it works! It'd be nice to have the underlying issue fixed, but this lets me work around it well enough.

**Comment by mhkeller** [comment]
I think I'll close this since this is a svelte issue and folks can still find it by searching the issue tracker. Thanks for the workaround @jackc
