### ISSUE TITLE
Pass count to `nice`

### ISSUE THREAD

**Issue by techniq** [mhkeller/layercake#99]
It would be helpful if you could pass the tick [count](https://github.com/d3/d3-scale#continuous_nice) to [yNice](https://layercake.graphics/guide#xnice) (et. al) instead of only a boolean and it would get set in [createScale()](https://github.com/mhkeller/layercake/blob/main/src/lib/helpers/createScale.js#L42).

So we would still support...
```svelte
<LayerCake yNice />
```
...which would call `.nice()`

but also support...
```svelte
<LayerCake yNice={4} />
```
...which would call `.nice(4)`

I created this REPL to [demonstrate](https://svelte.dev/repl/92e0fc6e7e6444c8b822c3af824cf085?version=3.50.1) the flexibility of passing the count to `nice`.

**Comment by techniq** [comment]
Also I was struggling to use [yPadding](https://layercake.graphics/guide#xpadding) to add some extra pixels to the scale (account for labels above the data point) but I'll open a separate issue once I've identified the root issue (or find out I'm doing something wrong :) ).

**Comment by mhkeller** [comment]
Ah yes good idea. I didn't realize you could pass a number to nice. That sounds like a good change. Thanks!

**Comment by techniq** [comment]
@mhkeller I'm always struggling with getting the domain to round/nice as I want, so finding this helped :), although I wished there was a better "round to the closest next tick".

For example, I would want the domain to nice to `300` but currently it goes to `260`.  You can see the results of nice() (and with an explicit count) in this [REPL](https://svelte.dev/repl/92e0fc6e7e6444c8b822c3af824cf085?version=3.50.1) but I hate having to provide an explicit count (as you don't always know how many will be rendered, at least from my understanding).

<img width="490" alt="image" src="https://user-images.githubusercontent.com/177476/192836322-8e7afc5a-4dfe-4995-ad24-0993d14f1b66.png">

**Comment by techniq** [comment]
Actually I forgot I explicit set `ticks` to a default of [4](https://github.com/techniq/layerchart/blob/master/src/lib/components/AxisY.svelte#L14) which if I wasn't, it would produce these ticks.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/177476/192839345-6262a9db-8a1d-449f-ba1b-39cb945ea068.png">

I always thought the default number of ticks was too high, and thus, after the change requested here, I can pass `yTicks={4}` and all will be good :).

I still need to figure out `yPadding` not working in my cases (to account for the label above the bar), but that's for another day.

**Comment by mhkeller** [comment]
yea ticks are definitely tough! D3 is a little mysterious in how it calculates them. I often end up supplying a list of exact values, especially for mobile and such. Four ticks is the default in my example components no? https://layercake.graphics/components/AxisY.svelte. I'll keep this issue open to track changing the argument type to the `nice` prop. If you sort out the padding issue, feel free to open another issu.e

**Comment by techniq** [comment]
You default to 4 as well (maybe where I got the idea) :).  I also support taking a [function](https://github.com/techniq/layerchart/blob/master/src/lib/components/AxisY.svelte#L28) which takes in the scale, which is useful to [calculate](https://github.com/techniq/layerchart/blob/d0d59c1449f922c523215cafffef344972a99b74/src/lib/utils/ticks.ts#L146-L177) the ticks based on the domain min/max (time series particularly).

```svelte
<AxisX ticks={(scale) => getMinorTicks(scale.domain()[0], scale.domain()[1])} />
```

**Comment by techniq** [comment]
@mhkeller if you haven't started this yet, I might be able to send you a PR tonight (or at least this week).

**Comment by mhkeller** [comment]
@techniq go for it altho if you had a second, i thought this could be a higher priority: https://github.com/mhkeller/layercake/issues/100

**Comment by techniq** [comment]
@mhkeller I've already started the `nice` change, and tbh, I haven't used WebGL myself (yet) :).

I'm looking to use the `yNice={4}` on a few visuals already so hoping to get it available soon.  I should have the PR available soon (although need to leave shortly).
